package com.lumagrade.app.editor

object PresetCatalog {
    val presets = listOf(
        PhotoPreset(
            id = "original",
            name = "Original",
            collection = "Base",
            swatchStart = 0xFF3B3D42,
            swatchEnd = 0xFF74777E,
            adjustments = Adjustments(),
        ),
        PhotoPreset(
            id = "clean_portrait",
            name = "Clean Portrait",
            collection = "Portrait",
            swatchStart = 0xFFF3C7AF,
            swatchEnd = 0xFFB78472,
            adjustments = Adjustments(
                exposure = 0.16f, contrast = -0.06f, highlights = -0.20f,
                shadows = 0.22f, whites = 0.08f, blacks = -0.04f,
                temperature = 0.08f, tint = 0.035f, vibrance = 0.11f,
                saturation = -0.035f, sharpen = 0.10f,
                highlightHue = 38f, highlightTone = 0.045f,
            ),
        ),
        PhotoPreset(
            id = "portra_warm",
            name = "Portra Warm",
            collection = "Film",
            swatchStart = 0xFFF2B28E,
            swatchEnd = 0xFF765446,
            adjustments = Adjustments(
                exposure = 0.08f, contrast = -0.10f, highlights = -0.26f,
                shadows = 0.18f, whites = -0.04f, blacks = 0.08f,
                temperature = 0.16f, tint = 0.045f, vibrance = 0.09f,
                saturation = -0.08f, fade = 0.10f, grain = 0.16f,
                shadowHue = 205f, shadowTone = 0.035f,
                highlightHue = 35f, highlightTone = 0.10f,
            ),
        ),
        PhotoPreset(
            id = "golden_hour",
            name = "Golden Hour",
            collection = "Warm",
            swatchStart = 0xFFFFD27A,
            swatchEnd = 0xFFB85E31,
            adjustments = Adjustments(
                exposure = 0.12f, contrast = 0.07f, highlights = -0.22f,
                shadows = 0.14f, whites = 0.12f, blacks = -0.08f,
                temperature = 0.27f, tint = 0.025f, vibrance = 0.18f,
                saturation = 0.04f, vignette = 0.12f, sharpen = 0.08f,
                highlightHue = 36f, highlightTone = 0.16f,
            ),
        ),
        PhotoPreset(
            id = "nordic_air",
            name = "Nordic Air",
            collection = "Clean",
            swatchStart = 0xFFD8E7EA,
            swatchEnd = 0xFF879BA0,
            adjustments = Adjustments(
                exposure = 0.24f, contrast = -0.13f, highlights = -0.28f,
                shadows = 0.30f, whites = 0.08f, blacks = 0.10f,
                temperature = -0.10f, tint = -0.025f, vibrance = -0.05f,
                saturation = -0.12f, fade = 0.08f,
                shadowHue = 198f, shadowTone = 0.075f,
            ),
        ),
        PhotoPreset(
            id = "coastal_film",
            name = "Coastal Film",
            collection = "Film",
            swatchStart = 0xFF9BD8D4,
            swatchEnd = 0xFFE8B379,
            adjustments = Adjustments(
                exposure = 0.08f, contrast = -0.04f, highlights = -0.18f,
                shadows = 0.20f, whites = 0.02f, blacks = 0.06f,
                temperature = 0.05f, tint = -0.035f, vibrance = 0.15f,
                saturation = -0.045f, fade = 0.11f, grain = 0.10f,
                shadowHue = 190f, shadowTone = 0.11f,
                highlightHue = 40f, highlightTone = 0.08f,
            ),
        ),
        PhotoPreset(
            id = "cocoa_matte",
            name = "Cocoa Matte",
            collection = "Editorial",
            swatchStart = 0xFFD3B198,
            swatchEnd = 0xFF513C36,
            adjustments = Adjustments(
                contrast = -0.08f, highlights = -0.30f, shadows = 0.12f,
                whites = -0.10f, blacks = 0.15f, temperature = 0.10f,
                tint = 0.035f, vibrance = -0.08f, saturation = -0.16f,
                fade = 0.18f, vignette = 0.08f, grain = 0.14f,
                shadowHue = 25f, shadowTone = 0.065f,
                highlightHue = 46f, highlightTone = 0.075f,
            ),
        ),
        PhotoPreset(
            id = "chrome_punch",
            name = "Chrome Punch",
            collection = "Modern",
            swatchStart = 0xFF63D5FF,
            swatchEnd = 0xFFFF4E68,
            adjustments = Adjustments(
                contrast = 0.24f, highlights = -0.16f, shadows = -0.05f,
                whites = 0.18f, blacks = -0.20f, temperature = -0.025f,
                vibrance = 0.30f, saturation = 0.045f, vignette = 0.10f,
                sharpen = 0.16f, shadowHue = 215f, shadowTone = 0.055f,
            ),
        ),
        PhotoPreset(
            id = "seoul_night",
            name = "Seoul Night",
            collection = "Night",
            swatchStart = 0xFF26C6DA,
            swatchEnd = 0xFFAE55FF,
            adjustments = Adjustments(
                exposure = 0.05f, contrast = 0.20f, highlights = -0.36f,
                shadows = 0.24f, whites = 0.10f, blacks = -0.18f,
                temperature = -0.12f, tint = 0.09f, vibrance = 0.28f,
                saturation = 0.06f, vignette = 0.22f, sharpen = 0.13f,
                shadowHue = 202f, shadowTone = 0.18f,
                highlightHue = 322f, highlightTone = 0.10f,
            ),
        ),
        PhotoPreset(
            id = "blue_hour",
            name = "Blue Hour",
            collection = "Night",
            swatchStart = 0xFF7697D6,
            swatchEnd = 0xFF172A5C,
            adjustments = Adjustments(
                exposure = -0.04f, contrast = 0.12f, highlights = -0.24f,
                shadows = 0.10f, whites = 0.04f, blacks = -0.14f,
                temperature = -0.24f, tint = 0.035f, vibrance = 0.13f,
                saturation = -0.04f, vignette = 0.20f,
                shadowHue = 220f, shadowTone = 0.16f,
                highlightHue = 192f, highlightTone = 0.06f,
            ),
        ),
        PhotoPreset(
            id = "street_35",
            name = "Street 35",
            collection = "Film",
            swatchStart = 0xFFE3B15D,
            swatchEnd = 0xFF343B45,
            adjustments = Adjustments(
                contrast = 0.16f, highlights = -0.34f, shadows = 0.08f,
                whites = 0.08f, blacks = -0.13f, temperature = 0.07f,
                tint = -0.025f, vibrance = 0.05f, saturation = -0.10f,
                fade = 0.06f, vignette = 0.13f, grain = 0.23f,
                sharpen = 0.08f, shadowHue = 205f, shadowTone = 0.055f,
                highlightHue = 44f, highlightTone = 0.08f,
            ),
        ),
        PhotoPreset(
            id = "forest_mist",
            name = "Forest Mist",
            collection = "Nature",
            swatchStart = 0xFFB7C9A5,
            swatchEnd = 0xFF355B4A,
            adjustments = Adjustments(
                exposure = 0.05f, contrast = -0.09f, highlights = -0.30f,
                shadows = 0.25f, whites = -0.06f, blacks = 0.05f,
                temperature = -0.035f, tint = -0.055f, vibrance = -0.02f,
                saturation = -0.11f, fade = 0.11f, grain = 0.08f,
                shadowHue = 158f, shadowTone = 0.10f,
                highlightHue = 62f, highlightTone = 0.055f,
            ),
        ),
        PhotoPreset(
            id = "desert_fade",
            name = "Desert Fade",
            collection = "Warm",
            swatchStart = 0xFFE6C08E,
            swatchEnd = 0xFF9A6554,
            adjustments = Adjustments(
                exposure = 0.12f, contrast = -0.12f, highlights = -0.18f,
                shadows = 0.18f, whites = 0.03f, blacks = 0.12f,
                temperature = 0.18f, tint = 0.03f, vibrance = -0.04f,
                saturation = -0.13f, fade = 0.16f, vignette = 0.07f,
                grain = 0.12f, shadowHue = 18f, shadowTone = 0.07f,
                highlightHue = 46f, highlightTone = 0.11f,
            ),
        ),
        PhotoPreset(
            id = "dream_pop",
            name = "Dream Pop",
            collection = "Creative",
            swatchStart = 0xFFFFA9D7,
            swatchEnd = 0xFF8DC8FF,
            adjustments = Adjustments(
                exposure = 0.14f, contrast = -0.18f, highlights = -0.22f,
                shadows = 0.24f, whites = 0.05f, blacks = 0.13f,
                temperature = -0.035f, tint = 0.11f, vibrance = 0.12f,
                saturation = -0.035f, fade = 0.15f,
                shadowHue = 205f, shadowTone = 0.11f,
                highlightHue = 326f, highlightTone = 0.13f,
            ),
        ),
        PhotoPreset(
            id = "cinematic_teal",
            name = "Cinema Teal",
            collection = "Cinematic",
            swatchStart = 0xFF3AAFA9,
            swatchEnd = 0xFFFF9D66,
            adjustments = Adjustments(
                exposure = -0.05f, contrast = 0.22f, highlights = -0.30f,
                shadows = 0.07f, whites = 0.06f, blacks = -0.19f,
                temperature = 0.02f, tint = -0.03f, vibrance = 0.12f,
                saturation = -0.06f, vignette = 0.20f, grain = 0.08f,
                sharpen = 0.10f, shadowHue = 188f, shadowTone = 0.18f,
                highlightHue = 30f, highlightTone = 0.12f,
            ),
        ),
        PhotoPreset(
            id = "mono_silver",
            name = "Mono Silver",
            collection = "B&W",
            swatchStart = 0xFFE3E3E3,
            swatchEnd = 0xFF2F3033,
            adjustments = Adjustments(
                contrast = 0.24f, highlights = -0.22f, shadows = 0.12f,
                whites = 0.14f, blacks = -0.20f, saturation = -1f,
                vignette = 0.12f, grain = 0.18f, sharpen = 0.14f,
            ),
        ),
        PhotoPreset(
            id = "mono_fade",
            name = "Mono Fade",
            collection = "B&W",
            swatchStart = 0xFFBDB9B0,
            swatchEnd = 0xFF585653,
            adjustments = Adjustments(
                contrast = -0.04f, highlights = -0.28f, shadows = 0.20f,
                whites = -0.04f, blacks = 0.15f, saturation = -1f,
                fade = 0.20f, grain = 0.24f,
                highlightHue = 42f, highlightTone = 0.035f,
            ),
        ),
    )

    fun byId(id: String): PhotoPreset = presets.firstOrNull { it.id == id } ?: presets.first()
}
